Allow to customize ping events priority via handle-motd-order
Limework/RedisBungee pull request #108
Opened 2024-06-22 18:41 UTC by dasavick

Currently, the bungee implementation is using NORMAL priority for the ping event handler, while the velocity implementation is using LAST. Regardless of which choice may be the better one, this is an inconsistency that this patch addresses by using NORMAL as the default for both platforms.

Additionally to addressing the inconsistency, this patch adds a new config option `handle-motd-order` which uses velocity's event priority nomenclature to allow configuring the behavior of the MOTD handling on both platforms.

In cases where there is a MOTD plugin that incorrectly overrides a player count using the local player count, one may choose to use order LAST to override the value back to the global player count.

In cases where there is a MOTD plugin that relies on a player count value from the ping response, one may choose to use order FIRST to make sure the response will have the correct global player count.

2024-07-04 14:50 UTC, ham1255 commented
Looks good

2024-07-04 14:53 UTC, ham1255 commented
> Currently, the bungee implementation is using NORMAL priority for the ping event handler, while the velocity implementation is using LAST. Regardless of which choice may be the better one, this is an inconsistency that this patch addresses by using NORMAL as the default for both platforms.

i think this happened when i have split internals to support proxies other than bungeecord

2024-07-05 00:16 UTC, ham1255 requested changes

2024-07-05 00:22 UTC, merged

2024-07-08 14:28 UTC, Ayouuuu commented
[private](https://github.com/ProxioDev/ValioBungee/pull/108/files#diff-c75e4116be2c7ffc6c5fce89a33c9db98b108d7f133f51f40f02e15057fea457R47-R63) method should be public

2024-07-08 15:47 UTC, ham1255 commented
yeah it was screw up on my part for not checking bungeecord impl correctly. *i didn't*